// <auto-generated />
using System;
using Escolar.Repositorio;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Escolar.Repositorio.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260828161206_Add_Auditoria_Alunos")]
    partial class Add_Auditoria_Alunos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Escolar.Repositorio.Entidades.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("AtualizadoPor")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CriadoPor")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Deletado")
                        .HasColumnType("bit");

                    b.Property<int>("PessoaId")
                        .HasColumnType("int");

                    b.Property<int>("TurmaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PessoaId")
                        .IsUnique();

                    b.HasIndex("TurmaId");

                    b.ToTable("Alunos", "Escolar");
                });

            modelBuilder.Entity("Escolar.Repositorio.Entidades.AlunoResponsavel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlunoId")
                        .HasColumnType("int");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("smalldatetime");

                    b.Property<Guid?>("AtualizadoPor")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("ContatoEmergencia")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("CriadoEm")
                        .HasColumnType("smalldatetime");

                    b.Property<Guid?>("CriadoPor")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Deletado")
                        .HasColumnType("bit");

                    b.Property<string>("Parentesco")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PessoaId")
                        .HasColumnType("int");

                    b.Property<bool>("PodeRetirarAluno")
                        .HasColumnType("bit");

                    b.Property<bool>("ResponsavelFinanceiro")
                        .HasColumnType("bit");

                    b.Property<bool>("ResponsavelPedagogico")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("PessoaId");

                    b.HasIndex("AlunoId", "PessoaId")
                        .IsUnique();

                    b.ToTable("AlunosResponsaveis", "Escolar");
                });

            modelBuilder.Entity("Escolar.Repositorio.Entidades.Disciplina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativa")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("smalldatetime");

                    b.Property<Guid?>("AtualizadoPor")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CriadoEm")
                        .HasColumnType("smalldatetime");

                    b.Property<Guid?>("CriadoPor")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Deletado")
                        .HasColumnType("bit");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Disciplinas", "Escolar");
                });

            modelBuilder.Entity("Escolar.Repositorio.Entidades.Endereco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CEP")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Complemento")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PessoaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PessoaId")
                        .IsUnique();

                    b.ToTable("Enderecos", "Escolar");
                });

            modelBuilder.Entity("Escolar.Repositorio.Entidades.Nota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlunoId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("smalldatetime");

                    b.Property<Guid?>("AtualizadoPor")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CriadoEm")
                        .HasColumnType("smalldatetime");

                    b.Property<Guid?>("CriadoPor")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataLancamento")
                        .HasColumnType("smalldatetime");

                    b.Property<bool>("Deletado")
                        .HasColumnType("bit");

                    b.Property<int>("DisciplinaId")
                        .HasColumnType("int");

                    b.Property<decimal>("PontosFeitos")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("ProfessorId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPontos")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("TurmaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.HasIndex("DisciplinaId");

                    b.HasIndex("ProfessorId");

                    b.HasIndex("TurmaId");

                    b.ToTable("Notas", "Escolar");
                });

            modelBuilder.Entity("Escolar.Repositorio.Entidades.Pessoa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("smalldatetime");

                    b.Property<Guid?>("AtualizadoPor")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CriadoEm")
                        .HasColumnType("smalldatetime");

                    b.Property<Guid?>("CriadoPor")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("smalldatetime");

                    b.Property<bool>("Deletado")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CPF")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("Telefone")
                        .IsUnique();

                    b.ToTable("Pessoas", "Escolar");
                });

            modelBuilder.Entity("Escolar.Repositorio.Entidades.Presenca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlunoId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("smalldatetime");

                    b.Property<Guid?>("AtualizadoPor")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CriadoEm")
                        .HasColumnType("smalldatetime");

                    b.Property<Guid?>("CriadoPor")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Data")
                        .HasColumnType("smalldatetime");

                    b.Property<bool>("Deletado")
                        .HasColumnType("bit");

                    b.Property<int>("DisciplinaId")
                        .HasColumnType("int");

                    b.Property<bool>("Presente")
                        .HasColumnType("bit");

                    b.Property<int>("ProfessorId")
                        .HasColumnType("int");

                    b.Property<int>("TurmaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.HasIndex("DisciplinaId");

                    b.HasIndex("ProfessorId");

                    b.HasIndex("TurmaId");

                    b.ToTable("Presencas", "Escolar");
                });

            modelBuilder.Entity("Escolar.Repositorio.Entidades.Turma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("smalldatetime");

                    b.Property<Guid?>("AtualizadoPor")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CriadoEm")
                        .HasColumnType("smalldatetime");

                    b.Property<Guid?>("CriadoPor")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Deletado")
                        .HasColumnType("bit");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Predio")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ResponsavelId")
                        .HasColumnType("int");

                    b.Property<string>("Sala")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ViceResponsavelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ResponsavelId");

                    b.HasIndex("ViceResponsavelId");

                    b.ToTable("Turmas", "Escolar");
                });

            modelBuilder.Entity("Escolar.Repositorio.Entidades.Aluno", b =>
                {
                    b.HasOne("Escolar.Repositorio.Entidades.Pessoa", "Pessoa")
                        .WithOne()
                        .HasForeignKey("Escolar.Repositorio.Entidades.Aluno", "PessoaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Escolar.Repositorio.Entidades.Turma", "Turma")
                        .WithMany("Alunos")
                        .HasForeignKey("TurmaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pessoa");

                    b.Navigation("Turma");
                });

            modelBuilder.Entity("Escolar.Repositorio.Entidades.AlunoResponsavel", b =>
                {
                    b.HasOne("Escolar.Repositorio.Entidades.Aluno", "Aluno")
                        .WithMany("Responsaveis")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Escolar.Repositorio.Entidades.Pessoa", "Responsavel")
                        .WithMany()
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Responsavel");
                });

            modelBuilder.Entity("Escolar.Repositorio.Entidades.Endereco", b =>
                {
                    b.HasOne("Escolar.Repositorio.Entidades.Pessoa", "Pessoa")
                        .WithOne("Endereco")
                        .HasForeignKey("Escolar.Repositorio.Entidades.Endereco", "PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("Escolar.Repositorio.Entidades.Nota", b =>
                {
                    b.HasOne("Escolar.Repositorio.Entidades.Aluno", "Aluno")
                        .WithMany("Notas")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Escolar.Repositorio.Entidades.Disciplina", "Disciplina")
                        .WithMany("Notas")
                        .HasForeignKey("DisciplinaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Escolar.Repositorio.Entidades.Pessoa", "Professor")
                        .WithMany()
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Escolar.Repositorio.Entidades.Turma", "Turma")
                        .WithMany()
                        .HasForeignKey("TurmaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Disciplina");

                    b.Navigation("Professor");

                    b.Navigation("Turma");
                });

            modelBuilder.Entity("Escolar.Repositorio.Entidades.Presenca", b =>
                {
                    b.HasOne("Escolar.Repositorio.Entidades.Aluno", "Aluno")
                        .WithMany("Presencas")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Escolar.Repositorio.Entidades.Disciplina", "Disciplina")
                        .WithMany("Presencas")
                        .HasForeignKey("DisciplinaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Escolar.Repositorio.Entidades.Pessoa", "Professor")
                        .WithMany()
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Escolar.Repositorio.Entidades.Turma", "Turma")
                        .WithMany()
                        .HasForeignKey("TurmaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Disciplina");

                    b.Navigation("Professor");

                    b.Navigation("Turma");
                });

            modelBuilder.Entity("Escolar.Repositorio.Entidades.Turma", b =>
                {
                    b.HasOne("Escolar.Repositorio.Entidades.Aluno", "Responsavel")
                        .WithMany()
                        .HasForeignKey("ResponsavelId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Escolar.Repositorio.Entidades.Aluno", "ViceResponsavel")
                        .WithMany()
                        .HasForeignKey("ViceResponsavelId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Responsavel");

                    b.Navigation("ViceResponsavel");
                });

            modelBuilder.Entity("Escolar.Repositorio.Entidades.Aluno", b =>
                {
                    b.Navigation("Notas");

                    b.Navigation("Presencas");

                    b.Navigation("Responsaveis");
                });

            modelBuilder.Entity("Escolar.Repositorio.Entidades.Disciplina", b =>
                {
                    b.Navigation("Notas");

                    b.Navigation("Presencas");
                });

            modelBuilder.Entity("Escolar.Repositorio.Entidades.Pessoa", b =>
                {
                    b.Navigation("Endereco");
                });

            modelBuilder.Entity("Escolar.Repositorio.Entidades.Turma", b =>
                {
                    b.Navigation("Alunos");
                });
#pragma warning restore 612, 618
        }
    }
}
