services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2025-latest
    container_name: sqlserver-dev
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "ALTERAR"
    ports:
      - "14330:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
      - ./backups:/backups

volumes:
  sqlserver_data: